### ISSUE TITLE
Compile Problem

### ISSUE THREAD

**Issue by Milalaa** [soytony/Point-Cloud-Preprocessing-Tools#1]
Hello! I have some questions while compiling this package, and I hope you can answer them.
When I run the cmake command.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/73516646/198958584-41c567ee-3741-4d82-b068-eb825be72cb8.png">
Then when I commented out CMakeLists.txt:30 and CMakeLists.txt:31, the following happens when I execute make -j6.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/73516646/198959178-d0948a45-d518-4314-a6dc-91f4dfdc2f2f.png">

**Comment by soytony** [comment]
I updated the link to third-party submodules, now it should work. 
flag `--recursive` is needed when cloning the repo, so that third-party submodules can be cloned as well.

**Comment by Milalaa** [comment]
> I updated the link to third-party submodules, now it should work. flag `--recursive` is needed when cloning the repo, so that third-party submodules can be cloned as well.

Thank you for your reply! I have successfully downloaded！
but I still meet some problems when I  execute make command.
<img width="1440" alt="截屏2022-11-04 10 29 49" src="https://user-images.githubusercontent.com/73516646/199873084-abb04eb2-98c8-4aae-a2f2-ab5546abb637.png">

<img width="1440" alt="截屏2022-11-04 10 30 14" src="https://user-images.githubusercontent.com/73516646/199873118-e203582b-978d-4cf1-9240-d5b778e8c0b9.png">
I have a very weak foundation in C++ and am still learning. Hope to get your guidance

**Comment by soytony** [comment]
It seems a compatibility issue caused by different versions of compilers, cuz it works fine on Ubuntu 20.04.  However, I removed usage of this type of initializer and you may try again. 
Let me know if there are any other issues with the repo. 
Thank you.

**Comment by Milalaa** [comment]
> It seems a compatibility issue caused by different versions of compilers, cuz it works fine on Ubuntu 20.04. However, I removed usage of this type of initializer and you may try again. Let me know if there are any other issues with the repo. Thank you.

I compiled it now successfully！Thank you！
